project_id = "rqtzrfbjbrucikhdatjy"

[functions.send-notification]
verify_jwt = false

[functions.webhook-capture]
verify_jwt = false

[functions.webhook-forward]
verify_jwt = false

[functions.push-to-sheets]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.webhook-retry]
verify_jwt = false

[functions.health-check]
verify_jwt = false
