// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hucfqmowvhusotacdyxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Y2ZxbW93dmh1c290YWNkeXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MDUyNjIsImV4cCI6MjA3MjQ4MTI2Mn0.vADXKSbtx-yeYgqeixo9GMQy5IsZ4Eo1y6tUhCtEpb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});